Parameters:
  ApplicationName:
    Description: The application name
    Type: String
  VPCId:
    Description: VPC to create security group into
    Type: AWS::EC2::VPC::Id

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 
        Fn::Sub: Security group for ${ApplicationName}
      SecurityGroupIngress:
        - CidrIp: "10.0.0.0/25"
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
          Description: SSH for engineering department
      VpcId: 
        Ref: VPCId

Outputs:
  SSHGroupId:
    Description: ID from security group
    Value: 
      Ref: SSHSecurityGroup
